## Tidy Up Scores

### Import Dependencies

In [1]:
import pandas as pd

### Import Data

In [51]:
df = pd.read_csv("8Scored.csv")

In [52]:
df = pd.DataFrame(df)

### First Look

In [53]:
df.head()

,review,score,rf_count,rf_ngram,rf_word,rf_char,xgb_count,xgb_ngram,xgb_word,xgb_char,cb_count,cb_ngram,cb_word,cb_chars
0,"The only problem, I actually counted the amoun...",4.0,[0],[0],[0],[0],[0],[0],[0],[0],[[0]],[[0]],[[0]],[[0]]
1,Me and my wife and my kids love them,5.0,[2],[2],[2],[2],[2],[2],[2],[2],[[2]],[[2]],[[2]],[[2]]
2,Definitely one of the best candies you can buy...,5.0,[2],[2],[2],[2],[2],[2],[2],[2],[[2]],[[2]],[[2]],[[2]]
3,"The price is great, but there are mostly grape...",3.0,[2],[2],[2],[2],[2],[2],[2],[2],[[2]],[[2]],[[2]],[[2]]
4,"Box and packaging in great shape, kids love them.",5.0,[2],[2],[2],[2],[2],[2],[2],[2],[[2]],[[2]],[[2]],[[2]]

In [56]:
df.tail()

,review,score,rf_count,rf_ngram,rf_word,rf_char,xgb_count,xgb_ngram,xgb_word,xgb_char,cb_count,cb_ngram,cb_word,cb_chars
4715,Love these bars,5.0,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos
4716,I have this product on a delivery schedule ver...,5.0,neg,pos,neg,pos,neg,neg,neg,neg,neg,neg,neg,pos
4717,Didnâ€™t realize when I purchased but product ex...,2.0,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos
4718,DELICIOUS!!,5.0,pos,pos,pos,pos,neg,neg,neg,neg,neg,neg,neg,neg
4719,Great price! This order has twice the amount o...,5.0,neg,pos,neg,pos,neg,neg,neg,neg,neg,neg,neg,neg

In [11]:
df.describe().T

        count      mean       std  min  25%  50%  75%  max
score  4720.0  3.976059  1.519966  1.0  3.0  5.0  5.0  5.0

### Change Rows

In [54]:
for i in range(2,14):
    df.iloc[:, i] = df.iloc[:, i].apply(lambda x: "neg" if (x== "[0]" or x== "[[0]]") else "neu" if (x== "[1]" or x== "[[1]]") else "pos")

In [55]:
df

,review,score,rf_count,rf_ngram,rf_word,rf_char,xgb_count,xgb_ngram,xgb_word,xgb_char,cb_count,cb_ngram,cb_word,cb_chars
0,"The only problem, I actually counted the amoun...",4.0,neg,neg,neg,neg,neg,neg,neg,neg,neg,neg,neg,neg
1,Me and my wife and my kids love them,5.0,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos
2,Definitely one of the best candies you can buy...,5.0,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos
3,"The price is great, but there are mostly grape...",3.0,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos
4,"Box and packaging in great shape, kids love them.",5.0,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4715,Love these bars,5.0,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos
4716,I have this product on a delivery schedule ver...,5.0,neg,pos,neg,pos,neg,neg,neg,neg,neg,neg,neg,pos
4717,Didnâ€™t realize when I purchased but product ex...,2.0,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos,pos
4718,DELICIOUS!!,5.0,pos,pos,pos,pos,neg,neg,neg,neg,neg,neg,neg,neg
4719,Great price! This order has twice the amount o...,5.0,neg,pos,neg,pos,neg,neg,neg,neg,neg,neg,neg,neg

### Export Csv

In [57]:
df.to_csv('9Scores.csv', index=False, header=True)